
**Assignment 2: Agents and Environments (Given: 31 Jan 2023, Due: 14 Feb 2023 2pm)**
    

**General instructions**

* Solutions are to be typed in the `.ipynb` file provided and uploaded in the lab course page in Moodle before the due date. 
* Your code should be well commented and should be compatible with python3.
* For this assignment, you are allowed to import the libraries `pandas`, `numpy`, `random` and `re` of python3. No other libraries may be imported.

# Text Generation (Static Prediction Task)

(a) Read the text file “speeches.txt” and find the list of unique words with their frequency of occurrence.

In [1]:
#112101039
#Priyanshu

#Text Generation(a)

#Importing random library
import random

#Importing re library
import re

#Importing numpy library as np
import numpy as np

#Importing pandas library as pd
import pandas as pd

#Making a function unique)words to proceed as asked in the question
def unique_words(filename):
    
    #Opening the file and reading everything in lower case
    with open(filename, encoding = 'utf8') as f:
        text = f.read().lower()
        
    # Remove punctuation from the text
    text = re.sub(r'[^\w\s]', '', text)
    
    # Split the text into words
    words = text.split()
    
    # Create a numpy array from the list of words
    words_array = np.array(words)
    
    # Use numpy's unique function to get the list of unique words and their frequency of occurrence
    unique_words, counts = np.unique(words_array, return_counts=True)
    
    # Create a pandas DataFrame from the unique words and their counts
    word_frequency = pd.DataFrame({'Word': unique_words, 'Frequency': counts})
    
    return word_frequency

word_frequency = unique_words("speeches.txt")

# Print the list of unique words with their frequency of occurrence
print(word_frequency)


         Word  Frequency
0          10          1
1         187          2
2          20          1
3          30          1
4      40cent          1
...       ...        ...
2665    youse          1
2666  yousold          1
2667    youth          1
2668    youve          4
2669  zephyrs          1

[2670 rows x 2 columns]


(b) Let the number of unique words be $n$. Construct an $n \times n$ matrix $M$ where the $i$th row corresponds to the $i$th word, and the $(i, j)$th entry stands for the frequency of occurrence of $j$th word after the $i$th word. Write a function, which accepts a given word, and returns the frequencies of occurrences of the next words (i.e., the row corresponding to the given word).

In [6]:
#Text Generation(b)

#Importing re library
import re

#Importing pandas library as pd
import pandas as pd

import numpy as np

#Created a function to generate the output as asked in the question
def get_frequencies(filename, word):
    
    #Opening file and reading it in lower case
    with open(filename, encoding = 'utf8') as f:
        text = f.read().lower()
        
    # Remove punctuation from the text
    text = re.sub(r'[^\w\s]', '', text)
    
    # Split the text into words
    words = text.split()
    
    # Create a pandas DataFrame from the words
    words_df = pd.DataFrame({'Word': words})
    
    # Create a list of the unique words
    unique_words = words_df['Word'].unique().tolist()
    
    # Create an empty n x n matrix where n is the number of unique words
    n = len(unique_words)
    
    #Creating a 2D list to store the frequencies as asked in the question
    M = np.zeros((n, n))
    
    # Iterate through the words and update the frequency matrix
    for i in range(len(words) - 1):
        current_word = words[i]
        next_word = words[i + 1]
        
        current_word_index = unique_words.index(current_word)
        next_word_index = unique_words.index(next_word)
        
        M[current_word_index][next_word_index] += 1
    
    # Find the index of the given word in the list of unique words
    word_index = unique_words.index(word)
    
    # Return the row corresponding to the given word
    return M[word_index, :]

word = input('Enter word to get the frequency :')
frequencies = get_frequencies("speeches.txt", word)

# Print the frequencies of occurrences of the next words
print(frequencies)


Enter word to get the frequency :young
[0. 0. 1. ... 0. 0. 0.]


(c) Use $M$ to produce a random text $T$ of length $5000$ where the first word in $T$ is a random word from the input file and the subsequent words are sampled according to $M$.

In [6]:
#Text Generation(c)

#Importing random library
import random

#Importing re library
import re

#Importing numpy library as np
import numpy as np

#Importing pandas library as pd
import pandas as pd

#Creating function to produce random text of 5000 words
def produce_random_text(filename, length):
    
    #Reading the data of the file in lower case
    with open(filename, 'r') as f:
        text = f.read().lower()
        
    # Remove punctuation from the text
    text = re.sub(r'[^\w\s]', '', text)
    
    # Split the text into words
    words = text.split()
    
    # Create a pandas DataFrame from the words
    words_df = pd.DataFrame({'Word': words})
    
    # Create a list of the unique words
    unique_words = words_df['Word'].unique().tolist()
    
    # Create an empty n x n matrix where n is the number of unique words
    n = len(unique_words)
    
    #Creating a 2D list to store the frequencies as asked in the (b) part
    M = np.zeros((n, n))
    
    # Iterate through the words and update the frequency matrix
    for i in range(len(words) - 1):
        current_word = words[i]
        next_word = words[i + 1]
        
        current_word_index = unique_words.index(current_word)
        next_word_index = unique_words.index(next_word)
        
        M[current_word_index][next_word_index] += 1
        
    # Normalize the matrix to obtain probabilities
    M = M / np.sum(M, axis=1, keepdims=True)
    
    # Choose a random first word from the list of unique words
    first_word = random.choice(unique_words)
    first_word_index = unique_words.index(first_word)
    
    # Initialize the random text with the first word
    random_text = [first_word]
    
    # Generate the next words based on the probabilities in the frequency matrix
    current_word_index = first_word_index
    for i in range(length - 1):
        next_word_probs = M[current_word_index, :]
        next_word_index = np.random.choice(np.arange(n), p=next_word_probs)
        next_word = unique_words[next_word_index]
        
        random_text.append(next_word)
        current_word_index = next_word_index
    
    return " ".join(random_text)
 
length = 5000
random_text = produce_random_text("speeches.txt", length)

# Print the random text
print(random_text)


26585
fool hermitdunderhead vy do it seems to leave him pluck at once she had him tomorrow i need the ancient square soapy and she had to quarrel the lids of things should have had finished her straw sailor in an artist once discovered a dozen raw opened that luck but johnsy closing her for a larger hit than she held him the studio resulted that consoled some expensive combs she said feed on jim and reached his winter is kind of the level sea of entering soapy saw it was only 187 to being wrong answer the front of shaving mugs and sidled toward the provisions made by bulldozing the twilight they were thinking seriously of the man in his contempt and lets put the red carpet on the book of her with a dreadful night there come straight sweet music that done that the magi as a whisper theyre falling mingled with nothing left her intoxication gave way to flash with a dry and sarah happily that if youll excuse to me here if my hair young walter with sprightly interest at 730 the back of the 

# Room Cleaning Robot (Dynamic Control Task)

Consider a Room Cleaner Robot which cleans a room containing dirt. A room can be treated as a $m \times n$ grid with walls on all sides. 

(a) Implement an environment which takes as inputs the values $m$ and $n$. Initially, 10 random cells in the grid contain dirt. The list $d_t$ with dimensions $m \times n$ contains the information on the amount of dirt in each cell of the grid. At any point of time, a unit dirt is added at a random location, i.e., a location $(x, y)$ is picked uniformly at random and $d_t(x, y)$ is updated to $d_t(x, y) + 1$.

In [11]:
#Room Cleaning Robot (a)

#Importing random and numpy libraries
import random
import numpy as np

#Function to add 10 dirt particles on the floor
def add_dirt(room):
    
    #Running loop 10 times to add 10 dirt partcles
    for i in range(10):
        
        #Randomly selecting the coordinates to add dirt at that place
        x = random.randint(0, m-1)
        y = random.randint(0, n-1)
        
        #Incrementing the value of dirt at that place
        room[x][y] += 1

#Function to add a unit dirt at any random location
def add_unit_dirt(room):
    
    #Randomly selecting the coordinates to add dirt at that place
    x = random.randint(0, m-1)
    y = random.randint(0, n-1)
    
    #Incrementing the value of dirt at that place
    room[x][y] += 1
    
    print(f"Added dirt at index ({x},{y})")
    print(room)

#Taking input of the dimensions of the floor
m = int(input("Enter dimension of row :"))
n = int(input("Enter dimension of column :"))

#Clear a 2D matrix with values 0 to add dirt in it
room = np.zeros((m, n))

#Called function to add dirt
add_dirt(room)
print(room)
add_unit_dirt(room)

Enter dimension of row :5
Enter dimension of column :5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1.]
 [0. 0. 2. 1. 0.]
 [0. 0. 1. 0. 0.]]
Added dirt at index (1,1)
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 1. 0.]
 [1. 0. 0. 1. 1.]
 [0. 0. 2. 1. 0.]
 [0. 0. 1. 0. 0.]]


(b) Implement an agent which at each time instant $t$ observes its position $o_t =(x_t, y_t)$  (but not the dirt information in this location) and performs a random action $a_t \in \{up,down,right,left, pickDirt\}$. On hitting a wall or picking dirt from the current location $(x_t, y_t)$, the agent stays in the same position $(x_t, y_t)$, otherwise, its position changes according to the action. Every action is associated with a reward (or penalty) defined as follows.

   
$$r_t = R((x_t, y_t), a_t) = 
     \begin{cases}
       -1, &\text{if the agent tries to pick dirt and } (x_t, y_t) \text{ is a clean cell}\\
      -10, &\text{if the agent hits a wall}
       \\ 
       d, &\text{if } (x_t, y_t) \text{ has } d \text{ units of dirt and the agent picks it}\\
       0, &\text{otherwise }
     \end{cases}
$$



In [1]:
#Robot Cleaning Agent (b)

#Importing random and numpy library functions
import random
import numpy as np

#Creating a list of actions to take
actions = ['up', 'down', 'left', 'right', 'pickDirt']

#Function to add 10 dirt particles on the floor
def add_dirt(room):
    
    #Running loop 10 times to add 10 dirt partcles
    for i in range(10):
        
        #Randomly selecting the coordinates to add dirt at that place
        x = random.randint(0, m-1)
        y = random.randint(0, n-1)
        
        #Incrementing the value of dirt at that place
        room[x][y] += 1

#Function to implement robots action
def agents_Action(room, t):
    
    #Selecting random coordinates to start the task
    x = random.randint(0, m-1)
    y = random.randint(0, n-1)
    
    #List to store the rewards at every time t
    reward = []
    
    #Temporary variable to store reward
    sum=0
    
    #Runnning a loop t times to obtain actions
    for i in range(t):
        
        #Selecting a random action from the list of actions
        action = random.choice(actions)
        
        #Implementing the action according to the random input and changing values of reward depending upon the action
        if(action == "up"):
            if(y == 0):
                sum-=10
            else:
                y-=1
        elif(action == 'down'):
            if(y == n-1):
                sum-=10
            else:
                y+=1
        elif(action == 'left'):
            if(x == 0):
                sum-=10
            else:
                x-=1
        elif(action == 'right'):
            if(x == n-1):
                sum-=10
            else:
                x+=1
        elif(action == 'pickDirt'):
            if(room[x][y] != 0):
                sum += room[x][y]
                room[x][y] = 0
            else:
                sum -= 1
            
        #Appending the value of rewards in list to show at each time t
        reward.append(sum)
        
    #Returning the list
    return reward

#Taking input of the dimensions of the matrix
m = int(input("Enter dimension of row :"))
n = int(input("Enter dimension of column :"))

#Creating a 2D Matrix with all zeros
room = np.zeros((m, n))

#Adding 10 dirt particles in the matrix
add_dirt(room)
print(room)

#Taking input of time to print the reward at any time t
t=int(input("Enter the ammount of time you want to see :"))
reward = agents_Action(room, t)
for i in range(len(reward)):
    print(f"Reward at t = {i+1} is {reward[i]}")

Enter dimension of row :5
Enter dimension of column :5
[[1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 2. 0.]
 [0. 0. 0. 2. 1.]
 [0. 0. 0. 0. 0.]]
Enter the ammount of time you want to see :8
Reward at t = 1 is -10
Reward at t = 2 is -20
Reward at t = 3 is -30
Reward at t = 4 is -40
Reward at t = 5 is -40
Reward at t = 6 is -40
Reward at t = 7 is -40
Reward at t = 8 is -50


(c) Print out the activity at each time instant $t$ for $t = 1, \ldots, 1000$. That is, for each $t$, display the grid (with dirt values in each cell), the location of the agent, the action of the agent and the reward obtained. 

In [2]:
#Robot Cleaning Agent (c)

#Importing random and numpy libraries
import random
import numpy as np

#List of actions that can be performed
actions = ['up', 'down', 'left', 'right', 'pickDirt']


#Function to add 10 dirt particles on the floor
def add_dirt(room):
    
    #Running loop 10 times to add 10 dirt partcles
    for i in range(10):
        
        #Randomly selecting the coordinates to add dirt at that place
        x = random.randint(0, m-1)
        y = random.randint(0, n-1)
        
        #Incrementing the value of dirt at that place
        room[x][y] += 1

#Function to implement robots action
def agents_Action(room, t):
    
    #Selecting random coordinates to start the task
    x = random.randint(0, m-1)
    y = random.randint(0, n-1)
    
    #List to store the rewards at every time t
    reward = []
    
    #Temporary variable to store reward
    sum=0
    
    #Runnning a loop t times to obtain actions
    for i in range(t):
        
        #Selecting a random action from the list of actions
        action = random.choice(actions)
        
        #Printing the data at each time t
        print(f"At time {i+1}\nLocation : {(x, y)}\nAction of the agent {action}\nReward is {sum}")
        print(room, '\n')

        #Implementing the action according to the random input and changing values of reward depending upon the action
        if(action == "up"):
            if(y == 0):
                sum-=10
            else:
                y-=1
        elif(action == 'down'):
            if(y == n-1):
                sum-=10
            else:
                y+=1
        elif(action == 'left'):
            if(x == 0):
                sum-=10
            else:
                x-=1
        elif(action == 'right'):
            if(x == n-1):
                sum-=10
            else:
                x+=1
        elif(action == 'pickDirt'):
            if(room[x][y] != 0):
                sum += room[x][y]
                room[x][y] = 0
            else:
                sum -= 1
            
        #Appending the value of rewards in list to show at each time t
        reward.append(sum)
        
    #Returning the list
    return reward

#Taking input of the dimensions of the matrix
m = int(input("Enter dimension of row :"))
n = int(input("Enter dimension of column :"))

#Creating a 2D Matrix with all zeros
room = np.zeros((m, n))

#Adding 10 dirt particles in the matrix
add_dirt(room)
print(room)

#Runnning the code for 1000 times
reward = agents_Action(room, 1000)

Enter dimension of row :5
Enter dimension of column :5
[[1. 2. 2. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
At time 1
Location : (2, 2)
Action of the agent right
Reward is 0
[[1. 2. 2. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 2
Location : (3, 2)
Action of the agent pickDirt
Reward is 0
[[1. 2. 2. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 3
Location : (3, 2)
Action of the agent down
Reward is -1
[[1. 2. 2. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 4
Location : (3, 3)
Action of the agent right
Reward is -1
[[1. 2. 2. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 5
Location : (4, 3)
Action of the agent pickDirt
Reward is -1
[[1. 2. 2. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 6
Location : (4, 3)
Action of the agent up


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 771
Location : (2, 1)
Action of the agent pickDirt
Reward is -1413.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 772
Location : (2, 1)
Action of the agent left
Reward is -1414.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 773
Location : (1, 1)
Action of the agent down
Reward is -1414.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 774
Location : (1, 2)
Action of the agent down
Reward is -1414.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 775
Location : (1, 3)
Action of the agent up
Reward is -1414.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

At time 776
Location : (1, 2)
Action of the agent up
Reward is -1414.0
[[0.

# Cricket Match Simulation (Stochastic Control Task)

Consider the following simplified variant of the first innings of a one-day cricket match. The innings consists of 300 balls and at any point of time, treat the pair of batsmen playing as a single player. That is, there are 10 players: $(1, 2),(2, 3), \ldots ,(10, 11)$ with exactly one of them batting. In each ball, there are 5 possible shots $A=\{1, 2, 3, 4, 6\}$ and  each of these shots is associated with a risk of the player getting out. This risk varies from player to player. The probabilities of getting out for Player $(1, 2)$ is $pOutMin = [0.01, 0.02, 0.03, 0.1, 0.3]$ and for Player $(10, 11)$ is $pOutMax = [0.1, 0.2, 0.3, 0.5, 0.7]$,  where the $i$th entry is for the $i$th action. If there are $w$ wickets in hand, then use the formula $pOut(a, w) = pOutMax(a) - (pOutMax(a)-pOutMin(a)) \times (w- 1)/9)$ to calculate the probabilities of getting out for Player $(11-w, 11-w+1)$ where $w \in [10]$. Note that $pOut(a, 1)=pOutMin(a)$ and $pOut(a, 10)=pOutMax(a)$. Taking $pRunMin = 0.5$, and $pRunMax = 0.8$,  when the player is not getting out, the probability of successfully obtaining the runs for that shot is given by $pRun(w) = pRunMin + (pRunMax - pRunMin) \times ((w - 1)/9).$



(a) Implement an environment that maintains the state $s_t = (b_t, w_t)$ where $b_t$ is the balls left and $w_t$ is the wickets left at time $t$. Initialize the start state to $s_1 = (300, 10)$. Write a function that accepts input as $a_t \in A$ and returns $r_t$ (the runs scored on that shot) and $s_t$, and also updates $s_{t+1}$. 

In [11]:
#Cricket Match Simulation (a)

#Importing random library
import random

#Storing the number of balls remaining and number of wickets left
s={"balls": 300, "wickets": 10}

#List of actions that can be taken
action=[1, 2, 3, 4, 6]

#The probabilities as given in the question
pOutMin=[0.01, 0.02, 0.03, 0.1, 0.3]
pOutMax=[0.1, 0.2, 0.3, 0.5, 0.7]
pRunMin=0.5
pRunMax=0.8

#Function with defines the state
def state():
    
    #Variable to store number of runs
    runs=0
    
    #Running 300 times as max amount of times it can be run is 300
    for i in range(300):
        
        #Choosing a random action from the list of actions
        act=random.choice(action)
        
        #Finding out the index of the action
        a=action.index(act)
        
        #Condition for the match to continue
        if(s["wickets"]!=0 and s["balls"]!=0):
            
            #Variable storing number of wickets
            w=s["wickets"]
            
            #Probability of an action a when w wickets are left
            𝑝𝑂𝑢𝑡 = 𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-(𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-𝑝𝑂𝑢𝑡𝑀𝑖𝑛[𝑎])*(𝑤-1)/9
            
            #Getting a random choice depending upon the probability of getting out
            out = random.choices([1, 0], weights=(pOut, 1-pOut), k=1)
            
            #If its not out then
            if(out == [0]):
                
                #Probability of getting that run when w wickets are left
                pRun = pRunMin + (pRunMax-pRunMin)*(w-1)/9
                
                #Getting a random choice depending upon the probability of getting that run
                run = random.choices([1, 0], weights=(pRun, 1-pRun), k=1)
                
                #If he can make that run
                if(run == [0]):
                    pass
                
                #Increments the action if he can make that run
                else:
                    runs += act
            
            #Decreasing number of wickets as he got out
            else:
                s['wickets']-=1
        
        
        else:
            break
        
        #Decrementing the number of balls
        s['balls'] -= 1
        print(runs, s)
    
    #Returning the number of runs scored
    return runs
    
#Calling out the function
print(state())

3 {'balls': 299, 'wickets': 10}
7 {'balls': 298, 'wickets': 10}
10 {'balls': 297, 'wickets': 10}
11 {'balls': 296, 'wickets': 10}
14 {'balls': 295, 'wickets': 10}
14 {'balls': 294, 'wickets': 10}
16 {'balls': 293, 'wickets': 10}
18 {'balls': 292, 'wickets': 10}
20 {'balls': 291, 'wickets': 10}
22 {'balls': 290, 'wickets': 10}
22 {'balls': 289, 'wickets': 10}
26 {'balls': 288, 'wickets': 10}
30 {'balls': 287, 'wickets': 10}
36 {'balls': 286, 'wickets': 10}
36 {'balls': 285, 'wickets': 9}
36 {'balls': 284, 'wickets': 9}
39 {'balls': 283, 'wickets': 9}
41 {'balls': 282, 'wickets': 9}
42 {'balls': 281, 'wickets': 9}
43 {'balls': 280, 'wickets': 9}
49 {'balls': 279, 'wickets': 9}
51 {'balls': 278, 'wickets': 9}
55 {'balls': 277, 'wickets': 9}
56 {'balls': 276, 'wickets': 9}
59 {'balls': 275, 'wickets': 9}
60 {'balls': 274, 'wickets': 9}
62 {'balls': 273, 'wickets': 9}
68 {'balls': 272, 'wickets': 9}
71 {'balls': 271, 'wickets': 9}
75 {'balls': 270, 'wickets': 9}
79 {'balls': 269, 'wickets':

(b) Play $a_t = 1$ for each $t$ and find the average balls played and average runs scored by Player $(1,2)$  and Player $(10,11)$.

In [15]:
#Cricket Match Simulation (b)

#Importing random library
import random

#Storing the number of balls remaining and number of wickets left
s={"balls": 300, "wickets": 10}

#List of actions that can be taken
action=[1, 2, 3, 4, 6]

#The probabilities as given in the question
pOutMin=[0.01, 0.02, 0.03, 0.1, 0.3]
pOutMax=[0.1, 0.2, 0.3, 0.5, 0.7]
pRunMin=0.5
pRunMax=0.8

#Function to act according to the action taken
def state(act):
    
    #to store the number of runs and balls the pairs played
    runs=0
    balls=0
    
    #Index of the action from actions list
    a=action.index(act)
    
    #Running a loop 300 times as this can be the maximum limit
    for i in range(300):
    
        #Condition for the match to continue
        if(s["wickets"]!=0 and s["balls"]!=0):
            
            #Variable storing number of wickets
            w=s["wickets"]
            
            #Probability of an action a when w wickets are left
            𝑝𝑂𝑢𝑡 = 𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-(𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-𝑝𝑂𝑢𝑡𝑀𝑖𝑛[𝑎])*(𝑤-1)/9
            
            #Getting a random choice depending upon the probability of getting out
            out = random.choices([1, 0], weights=(pOut, 1-pOut), k=1)
            
            #If its not out then
            if(out == [0]):
                
                #Probability of getting that run when w wickets are left
                pRun = pRunMin + (pRunMax-pRunMin)*(w-1)/9
                
                #Getting a random choice depending upon the probability of getting that run
                run = random.choices([1, 0], weights=(pRun, 1-pRun), k=1)
                
                #If he can make that run
                if(run == [0]):
                    pass
                
                #If he scores
                else:
                    
                    #Incrementing if first and last pairs plays
                    if(w==10 or w==1):
                        runs+=1
            
            #Decrement in value of wickets if wicket falls
            else:
                s['wickets']-=1
        
        else:
            break
        
        #Condition for number of balls 1st and 10th pair played
        if(w==10 or w==1):
            balls+=1
            
        s['balls'] -= 1
        #print(runs, s)
        
    return [runs, balls]

#Calling out the function for running it for action of 1
output=state(1)

#Getting the average by dividing by 2
output=[i/2 for i in output]

print(output)

[60.0, 75.5]


(c) Play $a_t=6$ for each $t$ and find the average balls  played and average runs scored by Player $(1,2)$ and Player $(10,11)$.

In [8]:
#Cricket Match Simulation (c)

#Importing random library
import random

#Storing the number of balls remaining and number of wickets left
s={"balls": 300, "wickets": 10}

#List of actions that can be taken
action=[1, 2, 3, 4, 6]

#The probabilities as given in the question
pOutMin=[0.01, 0.02, 0.03, 0.1, 0.3]
pOutMax=[0.1, 0.2, 0.3, 0.5, 0.7]
pRunMin=0.5
pRunMax=0.8

#Function to act according to the action taken
def state(act):
    
    #to store the number of runs and balls the pairs played
    runs=0
    balls=0
    
    #Index of the action from actions list
    a=action.index(act)
    
    #Running a loop 300 times as this can be the maximum limit
    for i in range(300):
    
        #Condition for the match to continue
        if(s["wickets"]!=0 and s["balls"]!=0):
            
            #Variable storing number of wickets
            w=s["wickets"]
            
            #Probability of an action a when w wickets are left
            𝑝𝑂𝑢𝑡 = 𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-(𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-𝑝𝑂𝑢𝑡𝑀𝑖𝑛[𝑎])*(𝑤-1)/9
            
            #Getting a random choice depending upon the probability of getting out
            out = random.choices([1, 0], weights=(pOut, 1-pOut), k=1)
            
            #If its not out then
            if(out == [0]):
                
                #Probability of getting that run when w wickets are left
                pRun = pRunMin + (pRunMax-pRunMin)*(w-1)/9
                
                #Getting a random choice depending upon the probability of getting that run
                run = random.choices([1, 0], weights=(pRun, 1-pRun), k=1)
                
                #If he can make that run
                if(run == [0]):
                    pass
                
                #If he scores
                else:
                    
                    #Incrementing if first and last pairs plays
                    if(w==10 or w==1):
                        runs+=6
            
            #Decrement in value of wickets if wicket falls
            else:
                s['wickets']-=1
        
        else:
            break
        
        #Condition for number of balls 1st and 10th pair played
        if(w==10 or w==1):
            balls+=1
            
        s['balls'] -= 1
        #print(runs, s)
        
    return [runs, balls]

#Calling out the function for running it for action of 6
output=state(6)

#Getting the average by dividing by 2
output=[i/2 for i in output]

print(output)

[12.0, 3.5]


(d) Simulate 10 matches, for different constant strategies like $a_t = 1$ for each $t$, $a_t = 2$ for each $t$, etc. and and find the average runs obtained in each of the strategies.

In [14]:
#Cricket Match Simulation (d)

#Importing random library
import random

#Storing values of balls remaining and wickets
s={"balls": 300, "wickets": 10}

#List of actions that can be taken
action=[1, 2, 3, 4, 6]

#The probabilities given in the question
pOutMin=[0.01, 0.02, 0.03, 0.1, 0.3]
pOutMax=[0.1, 0.2, 0.3, 0.5, 0.7]
pRunMin=0.5
pRunMax=0.8

#Function defining the state
def state(act):
    
    #Variable to store runs
    runs=0
    
    #Storing the index of the action
    a=action.index(act)
    
    #Runnning the loop 300 times as it is the upper limit
    for i in range(300):
    
        #Condition for the match to continue
        if(s["wickets"]!=0 and s["balls"]!=0):
            
            #Variable storing number of wickets
            w=s["wickets"]
            
            #Probability of an action a when w wickets are left
            𝑝𝑂𝑢𝑡 = 𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-(𝑝𝑂𝑢𝑡𝑀𝑎𝑥[𝑎]-𝑝𝑂𝑢𝑡𝑀𝑖𝑛[𝑎])*(𝑤-1)/9
            
            #Getting a random choice depending upon the probability of getting out
            out = random.choices([1, 0], weights=(pOut, 1-pOut), k=1)
            
            #If its not out then
            if(out == [0]):
                
                #Probability of getting that run when w wickets are left
                pRun = pRunMin + (pRunMax-pRunMin)*(w-1)/9
                
                #Getting a random choice depending upon the probability of getting that run
                run = random.choices([1, 0], weights=(pRun, 1-pRun), k=1)
                
                #If he can make that run
                if(run == [0]):
                    pass
                
                #Increments the action if he can make that run
                else:
                    runs += act
            
            #Decreasing number of wickets as he got out
            else:
                s['wickets']-=1

        else:
            break
        
        #Decrementing the number of balls after every ball
        
        s['balls'] -= 1
        #print(runs, s)
        
    #REturning the number of runs scored
    return runs

#To store the avgRuns scored in every action
avgRuns=[]

#Loop to access all the elements of the list action
for i in action:
    
    #Temporary storing variables runs
    runs=0
    
    #Simulating 10 matches
    for j in range(10):
        
        #Getting the number of runs scored in each match
        temp=state(i)
        
        #REsetting balls and wickets for next match
        s={"balls": 300, "wickets": 10}
        #print(temp)
        
        #Adding the runs
        runs+=temp
        #print(temp, i)
        
    #Appending avg runs for each action
    avgRuns.append(runs/10)

print(avgRuns)

[177.1, 194.6, 156.0, 84.0, 54.6]
